In [5]:
import tensorflow as tf 
import pandas as pd 
import matplotlib.pyplot as plt 
import seaborn as sns

## Data preprocessing

 training image preprocessing<!--  -->

In [6]:
training_set =tf.keras.utils.image_dataset_from_directory(
    'dataset/train',
    labels="inferred",
    label_mode="categorical",
    class_names=None,
    color_mode="rgb",
    batch_size=32,
    image_size=(128,128),
    shuffle=True,
    seed=None,
    validation_split=None,
    subset=None,
    interpolation="bilinear",
    follow_links=False,
    crop_to_aspect_ratio=False,
    pad_to_aspect_ratio=False,
    data_format=None,
    format="tf",
    verbose=True,
)


Found 49179 files belonging to 39 classes.


validation image preprocessing

In [7]:
validation_set =tf.keras.utils.image_dataset_from_directory(
    'dataset/val',
    labels="inferred",
    label_mode="categorical",
    class_names=None,
    color_mode="rgb",
    batch_size=32,
    image_size=(128,128),
    shuffle=True,
    seed=None,
    validation_split=None,
    subset=None,
    interpolation="bilinear",
    follow_links=False,
    crop_to_aspect_ratio=False,
    pad_to_aspect_ratio=False,
    data_format=None,
    format="tf",
    verbose=True,
)


Found 6139 files belonging to 39 classes.


In [8]:
training_set

<_PrefetchDataset element_spec=(TensorSpec(shape=(None, 128, 128, 3), dtype=tf.float32, name=None), TensorSpec(shape=(None, 39), dtype=tf.float32, name=None))>

In [9]:
for x,y in training_set: 
    print(x.shape )
    print(y.shape)
    break

(32, 128, 128, 3)
(32, 39)


# Building model

In [ ]:
from tensorflow.keras.layers import Dense,Conv2D,MaxPool2D,Flatten
from tensorflow.keras.models import Sequential

In [27]:
model =Sequential()

In [28]:
## Building convoluation layer 

In [30]:
model.add(Conv2D(filters=32,kernel_size=3,padding='same',activation='relu',input_shape=[128,128,3]))
model.add(Conv2D(filters=32,kernel_size=3,activation='relu'))
model.add(MaxPool2D(pool_size = 2,strides =2))
          

In [31]:
model.add(Conv2D(filters=64,kernel_size=3,padding='same',activation='relu',input_shape=[128,128,3]))
model.add(Conv2D(filters=64,kernel_size=3,activation='relu'))
model.add(MaxPool2D(pool_size = 2,strides =2))
          

In [32]:
model.add(Conv2D(filters=128,kernel_size=3,padding='same',activation='relu',input_shape=[128,128,3]))
model.add(Conv2D(filters=128,kernel_size=3,activation='relu'))
model.add(MaxPool2D(pool_size = 2,strides =2))
          

In [33]:
model.add(Conv2D(filters=256,kernel_size=3,padding='same',activation='relu',input_shape=[128,128,3]))
model.add(Conv2D(filters=256,kernel_size=3,activation='relu'))
model.add(MaxPool2D(pool_size = 2,strides =2))
          

In [34]:
model.add(Flatten())

In [35]:
model.add(Dense(units=1024,activation='relu'))

In [36]:
model.add(Dense(units=39,activation='softmax'))

## Model compiling 

In [37]:
model.compile(optimizer='adam',loss = 'categorical_crossentropy',metrics=['accuracy'])

In [38]:
model.summary()

Model: "sequential_1"

┏━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━┓
┃ Layer (type)                         ┃ Output Shape                ┃         Param # ┃
┡━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━┩
│ conv2d_10 (Conv2D)                   │ (None, 128, 128, 32)        │             896 │
├──────────────────────────────────────┼─────────────────────────────┼─────────────────┤
│ conv2d_11 (Conv2D)                   │ (None, 128, 128, 32)        │           9,248 │
├──────────────────────────────────────┼─────────────────────────────┼─────────────────┤
│ max_pooling2d_4 (MaxPooling2D)       │ (None, 64, 64, 32)          │               0 │
├──────────────────────────────────────┼─────────────────────────────┼─────────────────┤
│ conv2d_12 (Conv2D)                   │ (None, 64, 64, 32)          │           9,248 │
├──────────────────────────────────────┼─────────────────────────────┼─────────────────┤
│ conv2d_13 (Conv2D)                   │ (None, 62, 62, 32)          │           9,248 │
├──────────────────────────────────────┼─────────────────────────────┼─────────────────┤
│ max_pooling2d_5 (MaxPooling2D)       │ (None, 31, 31, 32)          │               0 │
├──────────────────────────────────────┼─────────────────────────────┼─────────────────┤
│ conv2d_14 (Conv2D)                   │ (None, 31, 31, 64)          │          18,496 │
├──────────────────────────────────────┼─────────────────────────────┼─────────────────┤
│ conv2d_15 (Conv2D)                   │ (None, 29, 29, 64)          │          36,928 │
├──────────────────────────────────────┼─────────────────────────────┼─────────────────┤
│ max_pooling2d_6 (MaxPooling2D)       │ (None, 14, 14, 64)          │               0 │
├──────────────────────────────────────┼─────────────────────────────┼─────────────────┤
│ conv2d_16 (Conv2D)                   │ (None, 14, 14, 128)         │          73,856 │
├──────────────────────────────────────┼─────────────────────────────┼─────────────────┤
│ conv2d_17 (Conv2D)                   │ (None, 12, 12, 128)         │         147,584 │
├──────────────────────────────────────┼─────────────────────────────┼─────────────────┤
│ max_pooling2d_7 (MaxPooling2D)       │ (None, 6, 6, 128)           │               0 │
├──────────────────────────────────────┼─────────────────────────────┼─────────────────┤
│ conv2d_18 (Conv2D)                   │ (None, 6, 6, 256)           │         295,168 │
├──────────────────────────────────────┼─────────────────────────────┼─────────────────┤
│ conv2d_19 (Conv2D)                   │ (None, 4, 4, 256)           │         590,080 │
├──────────────────────────────────────┼─────────────────────────────┼─────────────────┤
│ max_pooling2d_8 (MaxPooling2D)       │ (None, 2, 2, 256)           │               0 │
├──────────────────────────────────────┼─────────────────────────────┼─────────────────┤
│ flatten_1 (Flatten)                  │ (None, 1024)                │               0 │
├──────────────────────────────────────┼─────────────────────────────┼─────────────────┤
│ dense_2 (Dense)                      │ (None, 1024)                │       1,049,600 │
├──────────────────────────────────────┼─────────────────────────────┼─────────────────┤
│ dense_3 (Dense)                      │ (None, 39)                  │          39,975 │
└──────────────────────────────────────┴─────────────────────────────┴─────────────────┘

 Total params: 2,280,327 (8.70 MB)

 Trainable params: 2,280,327 (8.70 MB)

 Non-trainable params: 0 (0.00 B)

 # training model

In [39]:
trainig_history=model.fit(x = training_set,validation_data=validation_set,epochs=5)

Epoch 1/5
1537/1537 ━━━━━━━━━━━━━━━━━━━━ 842s 545ms/step - accuracy: 0.5395 - loss: 1.6440 - val_accuracy: 0.7558 - val_loss: 0.7938
Epoch 2/5
1537/1537 ━━━━━━━━━━━━━━━━━━━━ 1077s 701ms/step - accuracy: 0.8059 - loss: 0.6108 - val_accuracy: 0.8518 - val_loss: 0.4595
Epoch 3/5
1537/1537 ━━━━━━━━━━━━━━━━━━━━ 1566s 1s/step - accuracy: 0.8660 - loss: 0.4147 - val_accuracy: 0.8591 - val_loss: 0.4488
Epoch 4/5
1537/1537 ━━━━━━━━━━━━━━━━━━━━ 3659s 2s/step - accuracy: 0.8945 - loss: 0.3232 - val_accuracy: 0.8685 - val_loss: 0.4444
Epoch 5/5
1537/1537 ━━━━━━━━━━━━━━━━━━━━ 1032s 672ms/step - accuracy: 0.9123 - loss: 0.2616 - val_accuracy: 0.8922 - val_loss: 0.3403


In [41]:
model.save("training_model.keras")

 # some other metrics for model evaluation 

In [3]:
from tensorflow.keras.models import load_model

In [4]:
model = load_model("training_model.keras")

In [10]:
class_name = validation_set.class_names
class_name

['Apple___Apple_scab',
 'Apple___Black_rot',
 'Apple___Cedar_apple_rust',
 'Apple___healthy',
 'Background_without_leaves',
 'Blueberry___healthy',
 'Cherry___Powdery_mildew',
 'Cherry___healthy',
 'Corn___Cercospora_leaf_spot Gray_leaf_spot',
 'Corn___Common_rust',
 'Corn___Northern_Leaf_Blight',
 'Corn___healthy',
 'Grape___Black_rot',
 'Grape___Esca_(Black_Measles)',
 'Grape___Leaf_blight_(Isariopsis_Leaf_Spot)',
 'Grape___healthy',
 'Orange___Haunglongbing_(Citrus_greening)',
 'Peach___Bacterial_spot',
 'Peach___healthy',
 'Pepper,_bell___Bacterial_spot',
 'Pepper,_bell___healthy',
 'Potato___Early_blight',
 'Potato___Late_blight',
 'Potato___healthy',
 'Raspberry___healthy',
 'Soybean___healthy',
 'Squash___Powdery_mildew',
 'Strawberry___Leaf_scorch',
 'Strawberry___healthy',
 'Tomato___Bacterial_spot',
 'Tomato___Early_blight',
 'Tomato___Late_blight',
 'Tomato___Leaf_Mold',
 'Tomato___Septoria_leaf_spot',
 'Tomato___Spider_mites Two-spotted_spider_mite',
 'Tomato___Target_Spot'

In [11]:
test_set = tf.keras.utils.image_dataset_from_directory(
    'dataset/test',
    labels="inferred",
    label_mode="categorical",
    class_names=None,
    color_mode="rgb",
    batch_size=32,
    image_size=(128,128),
    shuffle=False,
    seed=None,
    validation_split=None,
    subset=None,
    interpolation="bilinear",
    follow_links=False,
    crop_to_aspect_ratio=False,
    pad_to_aspect_ratio=False,
    data_format=None,
    format="tf",
    verbose=True,
)

Found 6168 files belonging to 39 classes.


In [12]:
y_pred = model.predict(test_set)
y_pred

193/193 ━━━━━━━━━━━━━━━━━━━━ 37s 188ms/step


array([[4.9774647e-01, 4.1683572e-05, 1.4833345e-04, ..., 2.7380936e-06,
        1.8260514e-04, 4.7883217e-04],
       [5.5240840e-01, 6.9549783e-06, 3.0172606e-07, ..., 9.4052082e-09,
        1.9159766e-06, 5.2605683e-06],
       [5.1536288e-02, 1.8009371e-07, 3.5254125e-10, ..., 1.2329355e-09,
        1.0602243e-03, 2.4573787e-09],
       ...,
       [1.2648691e-11, 6.1809154e-16, 2.9712533e-15, ..., 6.8721159e-14,
        8.0656815e-15, 9.9999845e-01],
       [9.9836274e-13, 1.6634819e-16, 6.3942432e-16, ..., 8.0860177e-14,
        5.4898072e-14, 9.9999070e-01],
       [2.4242799e-09, 3.0984487e-13, 2.3248051e-12, ..., 6.5909250e-11,
        9.7837077e-12, 9.9986935e-01]], shape=(6168, 39), dtype=float32)

In [13]:
#  task is select maximum probabily class

In [16]:
predicted_categories = tf.argmax(y_pred,axis =1)

In [17]:
predicted_categories

<tf.Tensor: shape=(6168,), dtype=int64, numpy=array([ 0,  0, 17, ..., 38, 38, 38], shape=(6168,))>

In [18]:
true_categories = tf.concat([y for x,y in test_set],axis=0)
true_categories

<tf.Tensor: shape=(6168, 39), dtype=float32, numpy=
array([[1., 0., 0., ..., 0., 0., 0.],
       [1., 0., 0., ..., 0., 0., 0.],
       [1., 0., 0., ..., 0., 0., 0.],
       ...,
       [0., 0., 0., ..., 0., 0., 1.],
       [0., 0., 0., ..., 0., 0., 1.],
       [0., 0., 0., ..., 0., 0., 1.]], shape=(6168, 39), dtype=float32)>

In [19]:
y_true = tf.argmax(true_categories,axis =1)

In [21]:
y_true

<tf.Tensor: shape=(6168,), dtype=int64, numpy=array([ 0,  0,  0, ..., 38, 38, 38], shape=(6168,))>

In [24]:
from sklearn.metrics import  classification_report,confusion_matrix

In [23]:
print(classification_report(y_true,predicted_categories,target_names = class_name))

                                               precision    recall  f1-score   support

                           Apple___Apple_scab       0.90      0.70      0.79       100
                            Apple___Black_rot       0.91      0.94      0.93       100
                     Apple___Cedar_apple_rust       0.80      0.97      0.88       100
                              Apple___healthy       0.86      0.92      0.89       165
                    Background_without_leaves       0.80      0.96      0.87       115
                          Blueberry___healthy       0.91      0.99      0.95       151
                      Cherry___Powdery_mildew       0.99      0.91      0.95       106
                             Cherry___healthy       1.00      0.83      0.91       100
   Corn___Cercospora_leaf_spot Gray_leaf_spot       0.80      0.66      0.72       100
                           Corn___Common_rust       0.94      0.97      0.96       120
                  Corn___Northern_Leaf_Bli

In [26]:
cm = confusion_matrix(y_true,predicted_categories)

In [27]:
cm 

array([[ 70,   2,   0, ...,   0,   0,   0],
       [  0,  94,   1, ...,   0,   0,   0],
       [  0,   0,  97, ...,   0,   0,   0],
       ...,
       [  0,   0,   0, ..., 534,   0,   0],
       [  0,   0,   0, ...,   0,  96,   0],
       [  0,   0,   0, ...,   0,   0, 158]], shape=(39, 39))

In [28]:
# confution matrix visualization 

In [ ]:
plt.figure(figsize=(40,40))
sns.heatmap(cm,annot=True)
plt.xlabel("predicted class")
plt.ylable(" actual class")
plt.show()